Run API queries concurrently
developmentseed/federated-collection-discovery pull request #9
Opened 2024-07-23 16:03 UTC by hrodmn

The goal of this PR is to improve the response time for the `/search` endpoint by running the child API requests concurrently. Now it should be as fast as the slowest child API request rather than the cumulative response time of all child API requests.

- Run `get_collection_metadata` method for all `CatalogSearch` instances in a `ThreadPoolExecutor`
- **add script for benchmarking response time**:
  - on `main`: average runtime of 2.3 seconds
  - on `hr/async`: average runtime of 1.7 seconds
- **update docker mount/copy configuration**: this should prevent inadvertent dependency conflicts when mounting the `app` directory.

2024-07-23 23:00 UTC, chuckwondo requested changes
This looks nice! I'm blown away by how much you've written in a very short time, especially all of the testing code.

Most of my comments revolve around your Docker images. If you follow my suggestions, your server image size should drop from ~600M to ~300M, and your client image size should drop from ~2.16G to ~1.64G.

In conjunction, to reduce the volume of files transferred to the Docker context, add the following files:

`src/server/.dockerignore`:

```plain
*
!poetry.lock
!pyproject.toml
```

`src/client/.dockerignore`:

```plain
*
!package.json
!yarn.lock
```

2024-07-24 16:45 UTC, hrodmn commented on src/server/app/collection_search.py
> +    return itertools.chain.from_iterable(results)
Thanks! This felt needlessly complicated, your approach is much better.

2024-07-24 16:50 UTC, hrodmn commented
> This looks nice! I'm blown away by how much you've written in a very short time, especially all of the testing code.

Thanks @chuckwondo! The tests have made all of the other development faster since its so easy to know when I break something. It took me a while to add the async features to the tests, though. I've done it once before but the `lifespan` thing adds an extra layer that makes it more challenging.

> 
> Most of my comments revolve around your Docker images. If you follow my suggestions, your server image size should drop from ~600M to ~300M, and your client image size should drop from ~2.16G to ~1.64G.

Thanks for all of your suggestions here. I took your comments and overhauled the Dockerfiles and docker-compose.yaml, but I think that belongs in a follow-up PR!

2024-07-24 17:16 UTC, chuckwondo approved these changes

2024-07-24 17:29 UTC, merged